# Generated by Django 2.2.6 on 2019-10-16 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PubShoeBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'PUB_SHOE_BRAND',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PubSnkrsSize',
            fields=[
                ('style', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('brand', models.CharField(blank=True, max_length=10, null=True)),
                ('us_size', models.FloatField(blank=True, null=True)),
                ('cn_size', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'PUB_SNKRS_SIZE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PubSnkrsStyle',
            fields=[
                ('style_num', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('brand', models.CharField(blank=True, max_length=10, null=True)),
                ('style_name', models.CharField(blank=True, max_length=30, null=True)),
                ('style', models.CharField(blank=True, max_length=10, null=True)),
                ('remark', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'PUB_SNKRS_STYLE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ShipCnInfo',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('number', models.CharField(blank=True, max_length=20, null=True)),
                ('remark', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'SHIP_CN_INFO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ShipInfo',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('express', models.CharField(blank=True, max_length=10, null=True)),
                ('ship_num', models.CharField(blank=True, max_length=20, null=True)),
                ('fees', models.FloatField(blank=True, null=True)),
                ('ship_status', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'SHIP_INFO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SnkrsInstoreInfo',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('style_num', models.CharField(blank=True, max_length=20, null=True)),
                ('size', models.FloatField()),
                ('ori_price', models.FloatField()),
                ('exchange_rate', models.FloatField(blank=True, null=True)),
                ('fees', models.FloatField(blank=True, null=True)),
                ('final_price', models.FloatField(blank=True, null=True)),
                ('rmb', models.FloatField()),
                ('buyer', models.CharField(blank=True, max_length=10, null=True)),
                ('buy_date', models.DateField(blank=True, null=True)),
                ('store_location', models.CharField(blank=True, max_length=10, null=True)),
                ('purchase_method', models.CharField(blank=True, max_length=10, null=True)),
                ('card', models.CharField(blank=True, max_length=10, null=True)),
                ('remark', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'SNKRS_INSTORE_INFO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SnkrsOnlineInfo',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('style_num', models.CharField(blank=True, max_length=20, null=True)),
                ('size', models.FloatField(blank=True, null=True)),
                ('ori_price', models.FloatField(blank=True, null=True)),
                ('exchange_rate', models.FloatField(blank=True, null=True)),
                ('fees', models.FloatField(blank=True, null=True)),
                ('final_price', models.FloatField(blank=True, null=True)),
                ('rmb', models.FloatField(blank=True, null=True)),
                ('buyer', models.CharField(blank=True, max_length=10, null=True)),
                ('buy_date', models.DateField(blank=True, null=True)),
                ('website', models.CharField(blank=True, max_length=10, null=True)),
                ('order_num', models.CharField(blank=True, max_length=20, null=True)),
                ('destination', models.CharField(blank=True, max_length=10, null=True)),
                ('ship_status', models.CharField(blank=True, max_length=10, null=True)),
                ('card', models.CharField(blank=True, max_length=10, null=True)),
                ('remark', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'SNKRS_ONLINE_INFO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SnkrsSale',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('platform', models.CharField(blank=True, max_length=10, null=True)),
                ('sale_price', models.FloatField(blank=True, null=True)),
                ('fees', models.FloatField(blank=True, null=True)),
                ('final_price', models.FloatField(blank=True, null=True)),
                ('saler_ratio', models.FloatField(blank=True, null=True)),
                ('sale_date', models.DateField(blank=True, null=True)),
                ('remark', models.CharField(blank=True, max_length=50, null=True)),
                ('sale_photo', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'SNKRS_SALE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SnkrsWarehouse',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('sneakers_status', models.CharField(blank=True, max_length=10, null=True)),
                ('is_online', models.CharField(blank=True, max_length=1, null=True)),
                ('express', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'SNKRS_WAREHOUSE',
                'managed': False,
            },
        ),
    ]
