# Generated by Django 2.2.6 on 2019-10-22 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaceship', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.CharField(blank=True, max_length=50, verbose_name='Email'),
        ),
    ]
