# Generated by Django 2.2.6 on 2019-10-22 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaceship', '0002_userprofile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='names',
            field=models.CharField(blank=True, max_length=10, verbose_name='Names'),
        ),
    ]
