# Generated by Django 2.2.6 on 2019-10-22 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaceship', '0003_userprofile_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='invite_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='InviteCode'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='invite_people',
            field=models.CharField(blank=True, max_length=50, verbose_name='InvitePeople'),
        ),
    ]
