# Generated by Django 2.2.6 on 2019-10-22 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaceship', '0004_auto_20191022_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='alipay',
            field=models.CharField(blank=True, max_length=50, verbose_name='alipay'),
        ),
    ]
