# Generated by Django 2.2.6 on 2019-10-22 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaceship', '0005_userprofile_alipay'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='special_sign1',
            field=models.CharField(blank=True, max_length=50, verbose_name='special_sign1'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='special_sign2',
            field=models.CharField(blank=True, max_length=10, verbose_name='special_sign2'),
        ),
    ]
