# Generated by Django 2.2.6 on 2019-10-23 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaceship', '0006_auto_20191022_1729'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerWithSeller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=50, verbose_name='Username')),
                ('buyer', models.CharField(blank=True, max_length=50, verbose_name='Buyer')),
                ('nickname', models.CharField(blank=True, max_length=50, verbose_name='NickName')),
                ('status', models.CharField(blank=True, max_length=50, verbose_name='Status')),
                ('operator', models.CharField(blank=True, max_length=50, verbose_name='Operator')),
                ('operatortime', models.DateTimeField(auto_now=True, verbose_name='OperatorTime')),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='BuyInfo',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('size', models.CharField(blank=True, max_length=5, verbose_name='Size')),
                ('ori_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('exchange', models.DecimalField(decimal_places=2, max_digits=10)),
                ('buy_fees', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax', models.DecimalField(decimal_places=2, max_digits=10)),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('final_rmb', models.DecimalField(decimal_places=2, max_digits=10)),
                ('buyer', models.CharField(blank=True, max_length=5, verbose_name='Buyer')),
                ('remark', models.CharField(blank=True, max_length=128, verbose_name='Operator')),
                ('operator', models.CharField(blank=True, max_length=50, verbose_name='Operator')),
                ('operatortime', models.DateTimeField(auto_now=True, verbose_name='OperatorTime')),
            ],
        ),
        migrations.CreateModel(
            name='GoodsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=30, verbose_name='Category')),
                ('brand', models.CharField(blank=True, max_length=30, verbose_name='Brand')),
                ('styles', models.CharField(blank=True, max_length=1, verbose_name='Styles')),
                ('name', models.CharField(blank=True, max_length=128, verbose_name='Name')),
                ('sku', models.CharField(blank=True, max_length=50, verbose_name='Sku')),
                ('isopen', models.CharField(blank=True, max_length=1, verbose_name='IsOpen')),
                ('operator', models.CharField(blank=True, max_length=50, verbose_name='Operator')),
                ('operatortime', models.DateTimeField(auto_now=True, verbose_name='OperatorTime')),
                ('remark', models.CharField(blank=True, max_length=128, verbose_name='Operator')),
            ],
        ),
    ]
