# Generated by Django 2.2.6 on 2019-10-24 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spaceship', '0007_buyerwithseller_buyinfo_goodsinfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buyerwithseller',
            options={'verbose_name': 'Buyer and Seller'},
        ),
        migrations.AlterModelOptions(
            name='goodsinfo',
            options={'verbose_name': 'Goods Info'},
        ),
    ]
