# Generated by Django 2.2.6 on 2019-10-24 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaceship', '0008_auto_20191024_0247'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ids', models.CharField(max_length=20, verbose_name='Ids')),
                ('platform', models.CharField(blank=True, max_length=10, verbose_name='PlatForm')),
                ('sell_rmb', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sell_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('express_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('final_rmb', models.DecimalField(decimal_places=2, max_digits=10)),
                ('seller', models.CharField(blank=True, max_length=10, verbose_name='Seller')),
                ('sell_times', models.DecimalField(decimal_places=0, max_digits=10)),
                ('sell_date', models.DateTimeField(auto_now=True, verbose_name='SellDate')),
                ('operator', models.CharField(blank=True, max_length=50, verbose_name='Operator')),
                ('operatortime', models.DateTimeField(auto_now=True, verbose_name='OperatorTime')),
                ('remark', models.CharField(blank=True, max_length=128, verbose_name='Remark')),
            ],
        ),
        migrations.CreateModel(
            name='ShipInterInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ids', models.CharField(max_length=20, verbose_name='Ids')),
                ('ship_number', models.CharField(blank=True, max_length=50, verbose_name='ShipNumber')),
                ('ship_store', models.CharField(blank=True, max_length=50, verbose_name='ShipStore')),
                ('ship_status', models.CharField(blank=True, max_length=50, verbose_name='ShipStatus')),
                ('ship_unit', models.CharField(blank=True, max_length=50, verbose_name='ShipUnit')),
                ('ship_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('exchange_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ship_rmb', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cn_number', models.CharField(blank=True, max_length=50, verbose_name='CnNumber')),
                ('cn_store', models.CharField(blank=True, max_length=50, verbose_name='CnStore')),
                ('creat_date', models.DateTimeField(auto_now=True, verbose_name='CreatDate')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='UpdateDate')),
                ('operator', models.CharField(blank=True, max_length=50, verbose_name='Operator')),
                ('operatortime', models.DateTimeField(auto_now=True, verbose_name='OperatorTime')),
                ('remark', models.CharField(blank=True, max_length=128, verbose_name='Remark')),
            ],
        ),
        migrations.AddField(
            model_name='buyinfo',
            name='ids',
            field=models.CharField(default=1, max_length=20, verbose_name='Ids'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='buyinfo',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='buyinfo',
            name='remark',
            field=models.CharField(blank=True, max_length=128, verbose_name='Remark'),
        ),
    ]
