# Generated by Django 2.2.6 on 2019-10-26 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaceship', '0012_buyerwithseller_substatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyerwithseller',
            name='username',
            field=models.CharField(blank=True, default=1, max_length=50, verbose_name='Username'),
            preserve_default=False,
        ),
    ]
