# Generated by Django 2.2.6 on 2019-10-27 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaceship', '0015_userandnews_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='style',
            field=models.CharField(blank=True, max_length=30, verbose_name='Style'),
        ),
    ]
