# Generated by Django 2.2.6 on 2019-10-27 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spaceship', '0016_news_style'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='dst_user',
        ),
    ]
