# Generated by Django 2.2.6 on 2019-10-29 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spaceship', '0019_storeinfo_goods'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeinfo',
            name='goods',
        ),
        migrations.AddField(
            model_name='goodsinfo',
            name='buy_date',
            field=models.DateTimeField(auto_now=True, verbose_name='BuyDate'),
        ),
        migrations.AddField(
            model_name='goodsinfo',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='spaceship.StoreInfo'),
            preserve_default=False,
        ),
    ]
