# Generated by Django 2.2.6 on 2019-10-30 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spaceship', '0020_auto_20191029_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyinfo',
            name='buyer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='spaceship.BuyerWithSeller'),
        ),
    ]
