# Generated by Django 2.2.6 on 2019-11-01 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spaceship', '0022_buyermatchseller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyermatchseller',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abuyer', to='spaceship.BuyerWithSeller'),
        ),
        migrations.AlterField(
            model_name='buyermatchseller',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aseller', to='spaceship.BuyerWithSeller'),
        ),
    ]
