# Generated by Django 2.2.6 on 2019-11-03 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaceship', '0023_auto_20191101_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='time1',
            field=models.DateField(auto_now=True, verbose_name='Time1'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='time2',
            field=models.DateField(auto_now=True, verbose_name='Time2'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='time3',
            field=models.DateField(auto_now=True, verbose_name='Time3'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='time4',
            field=models.DateField(auto_now=True, verbose_name='Time4'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='time5',
            field=models.DateField(auto_now=True, verbose_name='Time5'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='time6',
            field=models.DateField(auto_now=True, verbose_name='Time6'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='time7',
            field=models.DateField(auto_now=True, verbose_name='Time7'),
        ),
    ]
